# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns a test landscape.
#'
#' @param nItems How many items.
#' @param landsize Size as a numeric (float).
#' @param nClusters How many clusters, an integer value.
#' @param clusterSpread Dispersal of items around cluster centres.
#' @param regen_time Regeneration time, in timesteps.
#' @return A data frame of the evolved population traits.
get_test_landscape <- function(nItems, landsize, nClusters, clusterSpread, regen_time) {
    .Call(`_ecoevomove1_get_test_landscape`, nItems, landsize, nClusters, clusterSpread, regen_time)
}

#' Run a simulation of fast and slow movement.
#' @description Run a simulation in which agents move on a landscape with
#' discrete food items and switch to area restricted search with some
#' probability, after encountering a food item.
#'
#' @param scenario The scenario: 0 for ecological scenario only, or 
#' 1 for evolved probability of switching to area restricted search.
#' @param popsize The population size.
#' @param nItems How many food items on the landscape.
#' @param landsize The size of the landscape as a numeric (double).
#' @param nClusters Number of clusters around which food is generated.
#' @param clusterSpread How dispersed food is around the cluster centre.
#' @param regen_time The item regeneration time.
#' @param tmax The number of timesteps per generation.
#' @param genmax The maximum number of generations per simulation.
#' @param ballisticGammaA Alpha parameter for a step length distribution
#' used to draw steps for agent ballistic movement.
#' @param ballisticGammaB Beta parameter for a step length distribution
#' used to draw steps for agent ballistic movement.
#' @param ballisticAngle Standard deviation of a normal distribution from
#' which turning angles are drawn in radians, for ballistic movement.
#' Should be smaller than `searchAngle`.
#' @param searchGammaA Alpha parameter for a step length distribution
#' used to draw steps for agent searching movement.
#' @param searchGammaB Beta parameter for a step length distribution
#' used to draw steps for agent searching movement.
#' @param searchAngle Standard deviation of a normal distribution from
#' which turning angles are drawn in radians, for searching movement.
#' Should be greater than `ballisticAngle`.
#' @param range_perception The range at which agents detect items.
#' @param costMove The energetic cost per distance moved.
#' @param tSearch The duration of area restricted search; this is fixed, while
#' the probability of switching to this mode varies.
#' @param pSearchSlow The probability of switching to search mode for so-called slow
#' agents.
#' @param pSearchFast The probability of switching to search mode for so-called fast
#' agents.
#' @param pStrategy The initial proportion of fast individuals in the population.
#' @param nThreads How many threads to parallelise over. Set to 1 to run on
#' the HPC Peregrine cluster.
#' @param dispersal A float value; the standard deviation of a normal
#' distribution centred on zero, which determines how far away from its parent
#' each individual is initialised. The standard value is 5 percent of the
#' landscape size (\code{landsize}), and represents local dispersal.
#' Setting this to 10 percent is already almost equivalent to global dispersal.
#' @param mProb The probability of mutation. The suggested value is 0.01.
#' While high, this may be more appropriate for a small population; change this
#' value and \code{popsize} to test the simulation's sensitivity to these values.
#' @param mSize Controls the mutational step size, and represents the scale
#' parameter of a Cauchy distribution. 
#' @return An S4 class, `simulation_output`, with simulation outcomes.
run_model <- function(scenario, popsize, nItems, landsize, nClusters, clusterSpread, regen_time, tmax, genmax, paramBallisticGammaA, paramBallisticGammaB, paramBallisticNormalSD, paramSearchGammaA, paramSearchGammaB, paramSearchNormalSD, range_perception, costMove, tSearch, pSearchSlow, pSearchFast, pStrategy, nThreads, dispersal, mProb, mSize) {
    .Call(`_ecoevomove1_run_model`, scenario, popsize, nItems, landsize, nClusters, clusterSpread, regen_time, tmax, genmax, paramBallisticGammaA, paramBallisticGammaB, paramBallisticNormalSD, paramSearchGammaA, paramSearchGammaB, paramSearchNormalSD, range_perception, costMove, tSearch, pSearchSlow, pSearchFast, pStrategy, nThreads, dispersal, mProb, mSize)
}

